[[patterns]]
id         = "からして"
name       = "からして"
jlpt       = "N1"
meaning_en = "Even; judging from"

[[patterns.steps]]
surface    = "から"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "為る"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

