[[patterns]]
id         = "か否か"
name       = "か否か"
jlpt       = "N1"
meaning_en = "Whether X or not"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "副助詞"

[[patterns.steps]]
surface    = "否"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "終助詞"

