[[patterns]]
id         = "が早いか"
name       = "が早いか"
jlpt       = "N1"
meaning_en = "As soon as; the moment; no sooner ~ than"

[[patterns.steps]]
surface    = "が"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "早い"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "終助詞"

