[[patterns]]
id         = "きらいがある"
name       = "きらいがある"
jlpt       = "N1"
meaning_en = "Have a tendency to; tend to; have a touch of ~; have a dash of ~; smack of ~; be slightly ~"

[[patterns.steps]]
surface    = "きらい"

[[patterns.steps]]
surface    = "が"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "有る"

