[[patterns]]
id         = "この上ない"
name       = "この上ない"
jlpt       = "N1"
meaning_en = "Extremely; utterly; very; so; cannot be more; extreme; utmost"

[[patterns.steps]]
surface    = "この"
pos1       = "連体詞"

[[patterns.steps]]
surface    = "上"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

