[[patterns]]
id         = "ずにはおかない"
name       = "ずにはおかない"
jlpt       = "N1"
meaning_en = "Be bound to; definitely; unmistakably; unquestionably; undoubtedly; without fail; without doubt"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ず"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "置く"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ない"

