[[patterns]]
id         = "たところで"
name       = "たところで"
jlpt       = "N1"
meaning_en = "Even if"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "た"

[[patterns.steps]]
surface    = "ところ"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

