[[patterns]]
id         = "だに"
name       = "だに"
jlpt       = "N1"
meaning_en = "Just; (not) even"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

