[[patterns]]
id         = "ったらない"
name       = "ったらない"
jlpt       = "N1"
meaning_en = "So; extremely; indescribably; indescribable; incredibly; awfully; terribly; cannot tell you/describe/etc. how; too much of"

[[patterns.steps]]
surface    = "っ"
pos1       = "補助記号"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "足る"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ない"

