[[patterns]]
id         = "ては"
name       = "ては"
jlpt       = "N1"
meaning_en = "If; when; because"

[[patterns.steps]]
surface    = "て"
pos1       = "接続詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

