[[patterns]]
id         = "でもあるまいし"
name       = "でもあるまいし"
jlpt       = "N1"
meaning_en = "You are not ~, so; it isn’t ~, so"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "有る"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "まい"

[[patterns.steps]]
surface    = "し"
pos1       = "助詞"
pos2       = "接続助詞"

