[[patterns]]
id         = "であれ"
name       = "であれ"
jlpt       = "N1"
meaning_en = "Whether X or Y; be it X or Y; or"

[[patterns.steps]]
surface    = "で"
pos1       = "接続詞"

[[patterns.steps]]
surface    = "あれ"
pos1       = "代名詞"

