[[patterns]]
id         = "とは言え"
name       = "とは言え"
jlpt       = "N1"
meaning_en = "Although (it is said that/someone says that); even though (it is said that/someone says that); admitting that; that being said; however; nevertheless"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

