[[patterns]]
id         = "といえども"
name       = "といえども"
jlpt       = "N1"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "ど"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

