[[patterns]]
id         = "という"
name       = "という"
jlpt       = "N1"
meaning_en = "Called; that says ~; that"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

