[[patterns]]
id         = "といい"
name       = "といい"
jlpt       = "N1"
meaning_en = "In terms of both ~ and ~; in terms of ~ as well as ~; from the perspective of both ~ and ~"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

