[[patterns]]
id         = "ともなく"
name       = "ともなく"
jlpt       = "N1"
meaning_en = "Without intending to; without paying much attention; unconsciously; mindlessly; don’t know (exactly) who/where/etc. (but); cannot tell (exactly) who/where/etc. (but); (to/from) no particular (person, etc.)"

[[patterns.steps]]
surface    = "とも"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

