[[patterns]]
id         = "となると"
name       = "となると"
jlpt       = "N1"
meaning_en = "When it comes to; if it is true that ~; if it is the case that ~; if it turns out that ~"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "成る"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "接続助詞"

