[[patterns]]
id         = "とばかりに"
name       = "とばかりに"
jlpt       = "N1"
meaning_en = "As if; as if to say that; as if ~ were convinced that; as if ~ believed that; as if ~ decided that"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "ばかり"
pos1       = "助詞"
pos2       = "副助詞"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

