[[patterns]]
id         = "と言っても"
name       = "と言っても"
jlpt       = "N1"
meaning_en = "Although ~ say/said that ~; even though ~ say/said that ~"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

