[[patterns]]
id         = "ないまでも"
name       = "ないまでも"
jlpt       = "N1"
meaning_en = "May not ~ but; even though ~ not; although ~ not"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

[[patterns.steps]]
surface    = "いま"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

