[[patterns]]
id         = "なくしては"
name       = "なくしては"
jlpt       = "N1"
meaning_en = "Without; if it were not for ~"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "無くす"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

