[[patterns]]
id         = "ならではの"
name       = "ならではの"
jlpt       = "N1"
meaning_en = "Impossible if it’s not ~; only possible with/by/at/etc.; not possible with/by/at/etc. other ~; very difficult with/by/at/etc. any other ~ but; you can expect only/at/from/etc.; unless"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "なり-断定"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
surface    = "の"
pos1       = "助詞"
pos2       = "格助詞"

