[[patterns]]
id         = "なり"
name       = "なり"
jlpt       = "N1"
meaning_en = "The moment; when; as soon as; soon after; no sooner ~ than"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "なり-断定"

