[[patterns]]
id         = "にとどまらず"
name       = "にとどまらず"
jlpt       = "N1"
meaning_en = "Doesn’t stop with ~; doesn’t end with ~; not limited to ~; going beyond ~; not only ~ (but also ~)"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "留まる"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ず"

