[[patterns]]
id         = "にひきかえ"
name       = "にひきかえ"
jlpt       = "N1"
meaning_en = "In contrast to ~; while; whereas"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "引き替える"

