[[patterns]]
id         = "にしたところで"
name       = "にしたところで"
jlpt       = "N1"
meaning_en = "Also; (even) for ~"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "為る"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "た"

[[patterns.steps]]
surface    = "ところ"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

