[[patterns]]
id         = "に越したことはない"
name       = "に越したことはない"
jlpt       = "N1"
meaning_en = "Nothing is better than; if possible; be the best; be ideal; the ~ the ~"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "越す"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "た"

[[patterns.steps]]
surface    = "こと"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

