[[patterns]]
id         = "に難くない"
name       = "に難くない"
jlpt       = "N1"
meaning_en = "Not hard; easy ~"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "難い"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

