[[patterns]]
id         = "に限らず"
name       = "に限らず"
jlpt       = "N1"
meaning_en = "Not limited to ~ (but also); not only ~ (but also)"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "限る"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ず"

