[[patterns]]
id         = "ねばならない"
name       = "ねばならない"
jlpt       = "N1"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ず"

[[patterns.steps]]
surface    = "ば"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "成る"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ない"

