[[patterns]]
id         = "ばこそ"
name       = "ばこそ"
jlpt       = "N1"
meaning_en = "it is precisely because ~ that ~; only because ~; to the extent that ~"

[[patterns.steps]]
surface    = "ば"
pos1       = "副詞"

[[patterns.steps]]
surface    = "こそ"
pos1       = "助詞"
pos2       = "係助詞"

