[[patterns]]
id         = "べくもない"
name       = "べくもない"
jlpt       = "N1"
meaning_en = "Impossible; there is no way for someone to ~; cannot be expected to"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "べし"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

