[[patterns]]
id         = "べからず"
name       = "べからず"
jlpt       = "N1"
meaning_en = "Shouldn’t; must not; ought not to ~; cannot; don’t ~"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "べし"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ず"

