[[patterns]]
id         = "べくして"
name       = "べくして"
jlpt       = "N1"
meaning_en = "Exactly as expected"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "べし"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "為る"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

