[[patterns]]
id         = "までもない"
name       = "までもない"
jlpt       = "N1"
meaning_en = "Not necessary (to bother) to; do not need (to go as far as) to; do not have to"

[[patterns.steps]]
surface    = "ま"
pos1       = "感動詞"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

