[[patterns]]
id         = "もさることながら"
name       = "もさることながら"
jlpt       = "N1"
meaning_en = "~ is one thing, but; it is true that ~, but; it is the case that ~, but; but more importantly"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
surface    = "さる"
pos1       = "連体詞"

[[patterns.steps]]
surface    = "こと"

[[patterns.steps]]
surface    = "ながら"
pos1       = "助詞"
pos2       = "接続助詞"

