[[patterns]]
id         = "ものを"
name       = "ものを"
jlpt       = "N1"
meaning_en = "Although; but"

[[patterns.steps]]
surface    = "もの"

[[patterns.steps]]
surface    = "を"
pos1       = "助詞"
pos2       = "格助詞"

