[[patterns]]
id         = "や否や"
name       = "や否や"
jlpt       = "N1"
meaning_en = "As soon as; no sooner ~ than; the moment; soon after; immediately after"

[[patterns.steps]]
surface    = "や"
pos1       = "助詞"
pos2       = "副助詞"

[[patterns.steps]]
surface    = "否"

[[patterns.steps]]
surface    = "や"
pos1       = "助詞"
pos2       = "副助詞"

