[[patterns]]
id         = "ようと"
name       = "ようと"
jlpt       = "N1"
meaning_en = "Even if; whatever/whoever/ etc.; no matter what/who/how/etc.; whether X or Y"

[[patterns.steps]]
surface    = "よう"
pos1       = "副詞"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

