[[patterns]]
id         = "をよそに"
name       = "をよそに"
jlpt       = "N1"
meaning_en = "Indifferent to ~; contrary to ~; ignoring ~; despite"

[[patterns.steps]]
surface    = "を"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "よそ"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

