[[patterns]]
id         = "を問わず"
name       = "を問わず"
jlpt       = "N1"
meaning_en = "Regardless of; irrespective of; without reference to; whether X or Y; whether X or not; whatever/whoever/etc.; no matter what/who/how/etc."

[[patterns.steps]]
surface    = "を"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "問う"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ず"

