[[patterns]]
id         = "を禁じ得ない"
name       = "を禁じ得ない"
jlpt       = "N1"
meaning_en = "Cannot hold; cannot hold back; cannot keep back; cannot help ~ing; cannot keep ~ from ~ing"

[[patterns.steps]]
surface    = "を"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "禁ずる"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "得る"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ない"

