[[patterns]]
id         = "んばかりに"
name       = "んばかりに"
jlpt       = "N1"
meaning_en = "As if ~ were about to ~; almost"

[[patterns.steps]]
surface    = "ん"
pos1       = "感動詞"

[[patterns.steps]]
surface    = "ばかり"
pos1       = "助詞"
pos2       = "副助詞"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

