[[patterns]]
id         = "故に"
name       = "故に"
jlpt       = "N1"
meaning_en = "Because; because of; due to; therefore"

[[patterns.steps]]
surface    = "故"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

