[[patterns]]
id         = "滅多に"
name       = "滅多に"
jlpt       = "N1"
meaning_en = "Rarely; seldom; hardly; almost never"

[[patterns.steps]]
pos1       = "形状詞"
base_form  = "滅多"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

