[[patterns]]
id         = "かと言うと"
name       = "かと言うと"
jlpt       = "N2"
meaning_en = "You would think that ~ but (that is not right)"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "終助詞"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "接続助詞"

