[[patterns]]
id         = "からには"
name       = "からには"
jlpt       = "N2"
meaning_en = "Once; now that ~; as long as ~; so long as ~; if"

[[patterns.steps]]
surface    = "から"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

