[[patterns]]
id         = "かのように"
name       = "かのように"
jlpt       = "N2"

[[patterns.steps]]
surface    = "かの"
pos1       = "連体詞"

[[patterns.steps]]
pos1       = "形状詞"
base_form  = "様"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

