[[patterns]]
id         = "ざるを得ない"
name       = "ざるを得ない"
jlpt       = "N2"
meaning_en = "Cannot help -ing; cannot (help) but; have no choice but to ~; have to"

[[patterns.steps]]
surface    = "ざる"

[[patterns.steps]]
surface    = "を"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "得る"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ない"

