[[patterns]]
id         = "だけに"
name       = "だけに"
jlpt       = "N2"
meaning_en = "And as one would expect; so (naturally); because"

[[patterns.steps]]
surface    = "だけ"
pos1       = "助詞"
pos2       = "副助詞"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

