[[patterns]]
id         = "とかで"
name       = "とかで"
jlpt       = "N2"
meaning_en = "For some reason like ~; saying something like ~; because ~ or something like that"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "副助詞"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

