[[patterns]]
id         = "どころではない"
name       = "どころではない"
jlpt       = "N2"
meaning_en = "Cannot; be simply impossible; simply don’t/doesn’t have time; be far from ~; anything but ~; no way; far from; be out of question"

[[patterns.steps]]
surface    = "どころ"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

