[[patterns]]
id         = "どころか"
name       = "どころか"
jlpt       = "N2"
meaning_en = "Far from; not just; even"

[[patterns.steps]]
surface    = "どころ"
pos1       = "助詞"
pos2       = "副助詞"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "副助詞"

