[[patterns]]
id         = "なしでは"
name       = "なしでは"
jlpt       = "N2"
meaning_en = "Without"

[[patterns.steps]]
surface    = "なし"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

