[[patterns]]
id         = "なしに"
name       = "なしに"
jlpt       = "N2"
meaning_en = "Without"

[[patterns.steps]]
surface    = "なし"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

