[[patterns]]
id         = "ないことには"
name       = "ないことには"
jlpt       = "N2"
meaning_en = "If ~ not ~ then; unless"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

[[patterns.steps]]
surface    = "こと"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

