[[patterns]]
id         = "にもかかわらず"
name       = "にもかかわらず"
jlpt       = "N2"
meaning_en = "Although; though; in spite of; despite; notwithstanding; nevertheless"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "関わる"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ず"

