[[patterns]]
id         = "にかかわらず"
name       = "にかかわらず"
jlpt       = "N2"
meaning_en = "Regardless of; independent of; without reference to; without distinguishing; whether X or Y; whether X or not; whatever/whoever/etc."

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "関わる"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ず"

