[[patterns]]
id         = "に応じた"
name       = "に応じた"
jlpt       = "N2"
meaning_en = "In response to; according to; depending on; appropriate for; suitable for; suited to; meet"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "応ずる"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "た"

