[[patterns]]
id         = "に反する"
name       = "に反する"
jlpt       = "N2"
meaning_en = "Against; contrary to; in contrast to; in violation of; while; whereas"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "反する"

