[[patterns]]
id         = "に従い"
name       = "に従い"
jlpt       = "N2"
meaning_en = "As, accordingly; in proportion to; in accordance with; following"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "従う"

