[[patterns]]
id         = "に過ぎない"
name       = "に過ぎない"
jlpt       = "N2"
meaning_en = "Nothing more than; not more than; mere; merely; only; just; as little/few as; that's all"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "過ぎる"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ない"

