[[patterns]]
id         = "はおろか"
name       = "はおろか"
jlpt       = "N2"
meaning_en = "Let alone; not only ~ (but also ~); not to mention; to say nothing of; never mind; much less"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "形状詞"
base_form  = "愚か"

