[[patterns]]
id         = "ばかりに"
name       = "ばかりに"
jlpt       = "N2"
meaning_en = "Simply because; just because; simply on account of ~"

[[patterns.steps]]
surface    = "ばかり"
pos1       = "助詞"
pos2       = "副助詞"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

