[[patterns]]
id         = "ものではない"
name       = "ものではない"
jlpt       = "N2"
meaning_en = "Shouldn’t; not possibly; naturally cannot; cannot bear"

[[patterns.steps]]
surface    = "もの"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

