[[patterns]]
id         = "ものか"
name       = "ものか"
jlpt       = "N2"
meaning_en = "Wish; wonder if; should"

[[patterns.steps]]
surface    = "もの"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "終助詞"

