[[patterns]]
id         = "ものの"
name       = "ものの"
jlpt       = "N2"
meaning_en = "Although; though; even though; but"

[[patterns.steps]]
surface    = "もの"

[[patterns.steps]]
surface    = "の"
pos1       = "助詞"
pos2       = "格助詞"

