[[patterns]]
id         = "ようでは"
name       = "ようでは"
jlpt       = "N2"
meaning_en = "If; if it is true that; if it is the case that"

[[patterns.steps]]
pos1       = "形状詞"
base_form  = "様"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

