[[patterns]]
id         = "をめぐって"
name       = "をめぐって"
jlpt       = "N2"

[[patterns.steps]]
surface    = "を"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "巡る"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

