[[patterns]]
id         = "うちに"
name       = "うちに"
jlpt       = "N3"
meaning_en = "While; before; during"

[[patterns.steps]]
surface    = "うち"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

