[[patterns]]
id         = "からなる"
name       = "からなる"
jlpt       = "N3"
meaning_en = "Consist of; be composed of"

[[patterns.steps]]
surface    = "から"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "成る"

