[[patterns]]
id         = "かな"
name       = "かな"
jlpt       = "N3"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "終助詞"

[[patterns.steps]]
surface    = "な"
pos1       = "助詞"
pos2       = "終助詞"

