[[patterns]]
id         = "がち"
name       = "がち"
jlpt       = "N3"
meaning_en = "Tend to; be prone to; be apt to; be liable to; be subject to; often"

[[patterns.steps]]
surface    = "がち"
pos1       = "接尾辞"

