[[patterns]]
id         = "くせに"
name       = "くせに"
jlpt       = "N3"
meaning_en = "Although; in spite of the fact that; and yet; but"

[[patterns.steps]]
surface    = "くせ"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

