[[patterns]]
id         = "ことにする"
name       = "ことにする"
jlpt       = "N3"
meaning_en = "Decide to"

[[patterns.steps]]
surface    = "こと"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "為る"

