[[patterns]]
id         = "ことはない"
name       = "ことはない"
jlpt       = "N3"
meaning_en = "There is no need to; not necessary; there is no possibility that; there is no chance to"

[[patterns.steps]]
surface    = "こと"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

