[[patterns]]
id         = "ことに"
name       = "ことに"
jlpt       = "N3"
meaning_en = "It is ~ that; I am ~ that; we are ~ that; to my/our ~; ~ly"

[[patterns.steps]]
surface    = "こと"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

