[[patterns]]
id         = "さえ"
name       = "さえ"
jlpt       = "N3"
meaning_en = "Even; if ~ only; if ~ just; as long as; the only thing ~ need is"

[[patterns.steps]]
surface    = "さえ"
pos1       = "助詞"
pos2       = "副助詞"

