[[patterns]]
id         = "ずとも"
name       = "ずとも"
jlpt       = "N3"
meaning_en = "Without ~ing; even if ~ not; if ~ not"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ず"

[[patterns.steps]]
surface    = "とも"
pos1       = "助詞"
pos2       = "接続助詞"

