[[patterns]]
id         = "そうになる"
name       = "そうになる"
jlpt       = "N3"
meaning_en = "Almost"

[[patterns.steps]]
surface    = "そう"
pos1       = "副詞"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "成る"

