[[patterns]]
id         = "たらどうですか"
name       = "たらどうですか"
jlpt       = "N3"
meaning_en = "Why don't you do ~?; what about doing ~?"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "た"

[[patterns.steps]]
surface    = "どう"
pos1       = "副詞"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "です"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "終助詞"

