[[patterns]]
id         = "つまり"
name       = "つまり"
jlpt       = "N3"
meaning_en = "That is (to say); namely; in short; to sum up; in other words; after all; that means"

[[patterns.steps]]
surface    = "つまり"
pos1       = "副詞"

