[[patterns]]
id         = "とも"
name       = "とも"
jlpt       = "N3"
meaning_en = "No matter ~ may be; even if; at ~ -est"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

