[[patterns]]
id         = "とは"
name       = "とは"
jlpt       = "N3"
meaning_en = "(not think/expect/etc.) that; (be surprised/be glad/regret/etc.) that"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

