[[patterns]]
id         = "というのは"
name       = "というのは"
jlpt       = "N3"
meaning_en = "Mean; the meaning of ~ is; what ~ means is"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "の"
pos1       = "助詞"
pos2       = "準体助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

