[[patterns]]
id         = "として"
name       = "として"
jlpt       = "N3"
meaning_en = "As; in the capacity of"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "為る"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

