[[patterns]]
id         = "とか"
name       = "とか"
jlpt       = "N3"
meaning_en = "And; or"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "副助詞"

