[[patterns]]
id         = "と共に"
name       = "と共に"
jlpt       = "N3"
meaning_en = "As well as; with; along with; at the same time; when, as; while"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "共"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

