[[patterns]]
id         = "どんなに"
name       = "どんなに"
jlpt       = "N3"
meaning_en = "How ~ (!)"

[[patterns.steps]]
pos1       = "形状詞"
base_form  = "どんな"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

