[[patterns]]
id         = "なければならない"
name       = "なければならない"
jlpt       = "N3"
meaning_en = "Have to; must; need"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

[[patterns.steps]]
surface    = "ば"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "成る"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ない"

