[[patterns]]
id         = "など"
name       = "など"
jlpt       = "N3"
meaning_en = "And so on; and the like; for example; things like ~"

[[patterns.steps]]
surface    = "など"
pos1       = "助詞"
pos2       = "副助詞"

