[[patterns]]
id         = "には"
name       = "には"
jlpt       = "N3"
meaning_en = "To; in order to; for; for the purpose of ~"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

