[[patterns]]
id         = "によると"
name       = "によると"
jlpt       = "N3"
meaning_en = "According to; based on"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "因る"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

