[[patterns]]
id         = "によらず"
name       = "によらず"
jlpt       = "N3"
meaning_en = "Without; without ~ing; regardless of; independently of; without reference to; whether X or Y; whether X or not; whatever/whoever/etc.; no matter what/who/how/etc."

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "因る"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ず"

