[[patterns]]
id         = "にしろ"
name       = "にしろ"
jlpt       = "N3"
meaning_en = "Even though (it is/was the case that); even if (it is true that); although (it is/was the case that); whatever/whoever/etc.; no matter what/who/how/etc.; whether X or Y"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "為る"

