[[patterns]]
id         = "における"
name       = "における"
jlpt       = "N3"
meaning_en = "At; on; in; during"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "於く"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "り"

