[[patterns]]
id         = "により"
name       = "により"
jlpt       = "N3"
meaning_en = "According to; due to; owing to; because of; depending on; from ~ to; by means of; on the basis of; with; by"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "因る"

