[[patterns]]
id         = "につれて"
name       = "につれて"
jlpt       = "N3"
meaning_en = "As; in proportion to; with"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "連れる"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

