[[patterns]]
id         = "に関して"
name       = "に関して"
jlpt       = "N3"
meaning_en = "Concerning; with regard to; about; on"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "関する"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

