[[patterns]]
id         = "ばよかった"
name       = "ばよかった"
jlpt       = "N3"
meaning_en = "I wish ~ had done something"

[[patterns.steps]]
surface    = "ば"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "良い"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "た"

