[[patterns]]
id         = "べきだ"
name       = "べきだ"
jlpt       = "N3"
meaning_en = "Should; ought to"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "べし"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

