[[patterns]]
id         = "ほうがいい"
name       = "ほうがいい"
jlpt       = "N3"
meaning_en = "Had better do something"

[[patterns.steps]]
surface    = "ほう"

[[patterns.steps]]
surface    = "が"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "良い"

