[[patterns]]
id         = "やら"
name       = "やら"
jlpt       = "N3"
meaning_en = "X and Y; things like X and Y; X, Y and so on; whether X or Y; whether X or not"

[[patterns.steps]]
surface    = "やら"
pos1       = "助詞"
pos2       = "副助詞"

