[[patterns]]
id         = "わけにはいかない"
name       = "わけにはいかない"
jlpt       = "N3"
meaning_en = "Cannot; cannot but ~; cannot help -ing; have no (other) choice but to ~"

[[patterns.steps]]
surface    = "わけ"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "行く"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ない"

