[[patterns]]
id         = "を中心に"
name       = "を中心に"
jlpt       = "N3"
meaning_en = "Centering around; around; focusing on; mainly; primarily; with ~ as the center; with ~ as the leader; with ~ as the primary ~; take the lead"

[[patterns.steps]]
surface    = "を"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "中心"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

