[[patterns]]
id         = "一方"
name       = "一方"
jlpt       = "N3"
meaning_en = "While; when; (but) at the same time; on the other hand; even though; although"

[[patterns.steps]]
surface    = "一方"
pos1       = "接続詞"

