[[patterns]]
id         = "一方で"
name       = "一方で"
jlpt       = "N3"
meaning_en = "While; when; (but) at the same time; on the other hand; even though; although"

[[patterns.steps]]
surface    = "一方"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

