[[patterns]]
id         = "一方だ"
name       = "一方だ"
jlpt       = "N3"
meaning_en = "Only; always; continue to; keep ~ing; be steadily ~ing; become ~er and ~er"

[[patterns.steps]]
surface    = "一方"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

