[[patterns]]
id         = "上で"
name       = "上で"
jlpt       = "N3"
meaning_en = "Upon ~; after ~"

[[patterns.steps]]
surface    = "上"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

