[[patterns]]
id         = "上に"
name       = "上に"
jlpt       = "N3"
meaning_en = "As well; in addition; besides; furthermore; moreover; not only ~ but also"

[[patterns.steps]]
surface    = "上"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

