[[patterns]]
id         = "代わりに"
name       = "代わりに"
jlpt       = "N3"
meaning_en = "Instead of; instead; but (to make up for ~); so (to make up for ~); in place of"

[[patterns.steps]]
surface    = "代わり"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

