[[patterns]]
id         = "恐れがある"
name       = "恐れがある"
jlpt       = "N3"
meaning_en = "It is feared (that); we fear (that); we are worried/concerned (that); there is a fear/risk/chance/concern/etc.; can; could; may; it is possible (that); be in danger of"

[[patterns.steps]]
surface    = "恐れ"

[[patterns.steps]]
surface    = "が"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "有る"

