#!/usr/bin/env python3
"""Enumerate the complete closed-class auxiliary universe of the embedded UniDic.

The binary embeds `unidic-mecab-2.1.2` via the `lindera-unidic` crate. This
script reads that exact dictionary's `lex.csv` and writes
`grammar/compiler/aux-inventory.json` — the authoritative census of every
closed-class auxiliary lemma the tokenizer can ever emit.

Why this is a PROOF of completeness, not a sample:
`unk.def` (the rule for out-of-dictionary words) can only assign a small set of
open-class POS to unknown input — never 助動詞. So every auxiliary the tokenizer
produces must already be a row in `lex.csv`. Enumerating lex.csv therefore
bounds the universe exactly. This script asserts that unk.def property so the
proof can't silently rot on a dictionary bump.

Closed-class scope (the categories that drive inflection/politeness/negation and
that grammar rules widen over):
  - pos1 == 助動詞                      (all auxiliaries)
  - pos1 == 形状詞 and pos2 == 助動詞語幹  (そう/みたい/よう stems)
  - pos1 == 形容詞 and pos2 == 非自立可能  (無い/良い/欲しい as auxiliaries)

Re-run manually after a dictionary upgrade; never automate it, or the universe
could change without anyone deciding to accept the change.
"""

from __future__ import annotations

import argparse
import hashlib
import io
import json
import sys
import tarfile
from pathlib import Path

DICTIONARY = "unidic-mecab-2.1.2"
LEX_MEMBER = f"{DICTIONARY}/lex.csv"
UNK_MEMBER = f"{DICTIONARY}/unk.def"

# 0-indexed columns in a UniDic mecab lex.csv row.
COL_POS1 = 4
COL_POS2 = 5
COL_LEMMA = 11  # 語彙素 — the tokenizer's base_form.

# POS categories that unk.def is allowed to emit for unknown words. If a future
# dictionary lets unknowns be tagged 助動詞, lex.csv would stop being a complete
# census and this script must fail loudly.
CLOSED_CLASS_POS1 = {"助動詞", "形状詞", "形容詞"}


def find_tarball() -> Path:
    candidates = sorted(
        Path("target").glob(f"debug/build/lindera-unidic-*/out/{DICTIONARY}.tar.gz")
    )
    if not candidates:
        candidates = sorted(Path("target").glob(f"**/{DICTIONARY}.tar.gz"))
    if not candidates:
        sys.exit(
            f"could not find {DICTIONARY}.tar.gz under target/; run `cargo build` first"
        )
    return candidates[0]


def read_member(tar: tarfile.TarFile, name: str) -> str:
    member = tar.extractfile(name)
    if member is None:
        sys.exit(f"{name} missing from dictionary archive")
    return io.TextIOWrapper(member, encoding="utf-8").read()


def is_closed_class(pos1: str, pos2: str) -> bool:
    return (
        pos1 == "助動詞"
        or (pos1 == "形状詞" and pos2 == "助動詞語幹")
        or (pos1 == "形容詞" and pos2 == "非自立可能")
    )


def main() -> None:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument(
        "--tarball",
        type=Path,
        default=None,
        help=f"path to {DICTIONARY}.tar.gz (default: auto-detect under target/)",
    )
    parser.add_argument(
        "--output",
        type=Path,
        default=Path("grammar/compiler/aux-inventory.json"),
        help="output census path",
    )
    args = parser.parse_args()

    tarball = args.tarball or find_tarball()
    digest = hashlib.sha256(tarball.read_bytes()).hexdigest()

    with tarfile.open(tarball, "r:gz") as tar:
        lex = read_member(tar, LEX_MEMBER)
        unk = read_member(tar, UNK_MEMBER)

    # Proof guard: unknown words can never be tagged with a closed-class POS.
    unk_pos1 = set()
    for line in unk.splitlines():
        fields = line.split(",")
        if len(fields) > COL_POS1:
            unk_pos1.add(fields[COL_POS1])
    leaked = CLOSED_CLASS_POS1 & unk_pos1
    if leaked:
        sys.exit(
            f"unk.def can assign closed-class POS {sorted(leaked)}; "
            "lex.csv is no longer a complete census — review before trusting it"
        )

    members: dict[tuple[str, str], dict] = {}
    for line in lex.splitlines():
        fields = line.split(",")
        if len(fields) <= COL_LEMMA:
            continue
        pos1, pos2, base_form = fields[COL_POS1], fields[COL_POS2], fields[COL_LEMMA]
        if not is_closed_class(pos1, pos2):
            continue
        key = (pos1, base_form)
        members.setdefault(key, {"pos1": pos1, "pos2": pos2, "base_form": base_form})

    ordered = sorted(members.values(), key=lambda m: (m["pos1"], m["base_form"]))
    document = {
        "schema_version": 1,
        "dictionary": DICTIONARY,
        "source_sha256": digest,
        "note": (
            "Complete closed-class auxiliary census of the embedded UniDic. "
            "Generated by tools/dump_aux_inventory.py; do not edit by hand. "
            "Every member must be classified in grammar/compiler/families.json "
            "(enforced by tools/test_families.py)."
        ),
        "member_count": len(ordered),
        "members": ordered,
    }

    args.output.parent.mkdir(parents=True, exist_ok=True)
    args.output.write_text(
        json.dumps(document, ensure_ascii=False, indent=2, sort_keys=False) + "\n",
        encoding="utf-8",
    )
    print(f"{len(ordered)} closed-class auxiliary members -> {args.output}")
    print(f"dictionary {DICTIONARY} sha256 {digest}")


if __name__ == "__main__":
    main()
