[[patterns]]
id         = "あえて"
name       = "あえて"
jlpt       = ""
meaning_en = "Daringly; boldly; dare to ~; venture to ~; force oneself to ~"

[[patterns.steps]]
surface    = "あえて"
pos1       = "副詞"

