[[patterns]]
id         = "あくまでも"
name       = "あくまでも"
jlpt       = ""
meaning_en = "to the end; persistently; insist; strictly; just; under any circumstance; absolutely; never; completely; ultimately"

[[patterns.steps]]
surface    = "あくまで"
pos1       = "副詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

