[[patterns]]
id         = "あたかも"
name       = "あたかも"
jlpt       = ""
meaning_en = "(just) as if ~ were; (just) as if ~ did ~; just like; just; exactly"

[[patterns.steps]]
surface    = "あたかも"
pos1       = "副詞"

