[[patterns]]
id         = "あげくに"
name       = "あげくに"
jlpt       = ""
meaning_en = "in the end; finally; eventually; after"

[[patterns.steps]]
surface    = "あげく"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

