[[patterns]]
id         = "いかなる"
name       = "いかなる"
jlpt       = ""
meaning_en = "What kind of ~; no matter what ~; whatever; any kind of"

[[patterns.steps]]
surface    = "いかなる"
pos1       = "連体詞"

