[[patterns]]
id         = "いかにも"
name       = "いかにも"
jlpt       = ""
meaning_en = "Really; truly; indeed"

[[patterns.steps]]
surface    = "いかに"
pos1       = "副詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

