[[patterns]]
id         = "おく"
name       = "おく"
jlpt       = ""
meaning_en = "Do something in advance; go ahead and do something; let someone/something remain as he/it is"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "置く"

