[[patterns]]
id         = "およそ"
name       = "およそ"
jlpt       = ""
meaning_en = "Generally; commonly; all; quite entirely; totally; utterly; (not) at all; for the most part; mostly; almost; approximately; roughly; about; rough; general"

[[patterns.steps]]
surface    = "およそ"
pos1       = "副詞"

