[[patterns]]
id         = "からなっている"
name       = "からなっている"
jlpt       = ""
meaning_en = "Consist of; be composed of"

[[patterns.steps]]
surface    = "から"
pos1       = "接続詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "成る"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "居る"

