[[patterns]]
id         = "からと言って"
name       = "からと言って"
jlpt       = ""
meaning_en = "Just because; even if; even though"

[[patterns.steps]]
surface    = "から"
pos1       = "接続詞"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

