[[patterns]]
id         = "けれども"
name       = "けれども"
jlpt       = ""
meaning_en = "Although; though"

[[patterns.steps]]
surface    = "けれど"
pos1       = "接続詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

