[[patterns]]
id         = "ことで"
name       = "ことで"
jlpt       = ""
meaning_en = "By V-ing; because; result in; cause"

[[patterns.steps]]
surface    = "こと"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

