[[patterns]]
id         = "さすが"
name       = "さすが"
jlpt       = ""
meaning_en = "As might be expected; after all; it is only natural that ~; naturally; truly; really; indeed; impressive"

[[patterns.steps]]
surface    = "さすが"
pos1       = "副詞"

