[[patterns]]
id         = "さぞ"
name       = "さぞ"
jlpt       = ""
meaning_en = "I believe/I’m sure/I’m certain ~ very/really/truly ~; must be very/really/truly ~"

[[patterns.steps]]
surface    = "さぞ"
pos1       = "副詞"

