[[patterns]]
id         = "さぞかし"
name       = "さぞかし"
jlpt       = ""
meaning_en = "I believe/I’m sure/I’m certain ~ very/really/truly ~; must be very/really/truly ~"

[[patterns.steps]]
surface    = "さぞかし"
pos1       = "副詞"

