[[patterns]]
id         = "したがって"
name       = "したがって"
jlpt       = ""
meaning_en = "Therefore; accordingly; consequently"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "従う"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

