[[patterns]]
id         = "しかも"
name       = "しかも"
jlpt       = ""
meaning_en = "Moreover; furthermore; besides; on top of that; what's more; what's worse; more surprisingly; at that; nevertheless; and yet; even so"

[[patterns.steps]]
surface    = "しかも"
pos1       = "接続詞"

