[[patterns]]
id         = "すぐ"
name       = "すぐ"
jlpt       = ""
meaning_en = "At once; soon; right away; immediately; readily; instantly; easily; right"

[[patterns.steps]]
surface    = "すぐ"
pos1       = "副詞"

