[[patterns]]
id         = "ずして"
name       = "ずして"
jlpt       = ""
meaning_en = "Without ~ing; before (~ing); with no ~; if ~ do not; when ~ do not"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ず"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "為る"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

