[[patterns]]
id         = "そのもの"
name       = "そのもの"
jlpt       = ""
meaning_en = "Itself; themselves; very; perfect; the definition of; the picture of; absolutely; totally; utterly; perfectly"

[[patterns.steps]]
surface    = "その"
pos1       = "連体詞"

[[patterns.steps]]
surface    = "もの"

