[[patterns]]
id         = "そうかと言って"
name       = "そうかと言って"
jlpt       = ""
meaning_en = "But; yet; even so"

[[patterns.steps]]
surface    = "そう"
pos1       = "副詞"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "終助詞"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

