[[patterns]]
id         = "それでも"
name       = "それでも"
jlpt       = ""
meaning_en = "Nevertheless; yet; but in spite of that; even so"

[[patterns.steps]]
surface    = "それ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

