[[patterns]]
id         = "それとも"
name       = "それとも"
jlpt       = ""
meaning_en = "Or; either ~ or ~"

[[patterns.steps]]
surface    = "それ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

