[[patterns]]
id         = "それで"
name       = "それで"
jlpt       = ""
meaning_en = "And; because of that; that is why; therefore; so"

[[patterns.steps]]
surface    = "それ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

