[[patterns]]
id         = "それが"
name       = "それが"
jlpt       = ""
meaning_en = "Well (contrary to your expectation; I'm afraid to say this, but)"

[[patterns.steps]]
surface    = "それ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "が"
pos1       = "助詞"
pos2       = "格助詞"

