[[patterns]]
id         = "それから"
name       = "それから"
jlpt       = ""
meaning_en = "After that; and then; in addition to that"

[[patterns.steps]]
surface    = "それ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "から"
pos1       = "助詞"
pos2       = "格助詞"

