[[patterns]]
id         = "そもそもの"
name       = "そもそもの"
jlpt       = ""
meaning_en = "In the first place; to begin with; first of all; the very (beginning/origin/etc.); original; first; fundamental"

[[patterns.steps]]
surface    = "そもそも"

[[patterns.steps]]
surface    = "の"
pos1       = "助詞"
pos2       = "格助詞"

