[[patterns]]
id         = "そうになった"
name       = "そうになった"
jlpt       = ""
meaning_en = "Almost"

[[patterns.steps]]
surface    = "そう"
pos1       = "副詞"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "成る"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "た"

