[[patterns]]
id         = "その上"
name       = "その上"
jlpt       = ""
meaning_en = "On top of that; besides; moreover; furthermore; what's more; what's worse; not only ~ but also"

[[patterns.steps]]
surface    = "その"
pos1       = "連体詞"

[[patterns.steps]]
surface    = "上"

