[[patterns]]
id         = "それどころか"
name       = "それどころか"
jlpt       = ""
meaning_en = "On the contrary; far from that; as a matter of fact"

[[patterns.steps]]
surface    = "それ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "どころ"
pos1       = "助詞"
pos2       = "副助詞"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "副助詞"

