[[patterns]]
id         = "それに"
name       = "それに"
jlpt       = ""
meaning_en = "(and) in addition; moreover; furthermore; what's more; on top of that"

[[patterns.steps]]
surface    = "それ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

