[[patterns]]
id         = "それも"
name       = "それも"
jlpt       = ""
meaning_en = "What's more; what's worse; at that; furthermore; moreover; on top of that"

[[patterns.steps]]
surface    = "それ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

