[[patterns]]
id         = "それは"
name       = "それは"
jlpt       = ""
meaning_en = "(yes,) naturally; (yes,) of course; oh, surely"

[[patterns.steps]]
surface    = "それ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

