[[patterns]]
id         = "それだけ"
name       = "それだけ"
jlpt       = ""
meaning_en = "That much; to the same extent; to the same degree; equally"

[[patterns.steps]]
surface    = "それ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "だけ"
pos1       = "助詞"
pos2       = "副助詞"

