[[patterns]]
id         = "そこで"
name       = "そこで"
jlpt       = ""
meaning_en = "Then; at that time"

[[patterns.steps]]
surface    = "そこ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

