[[patterns]]
id         = "それでは"
name       = "それでは"
jlpt       = ""
meaning_en = "If so; then; well then"

[[patterns.steps]]
surface    = "それ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

