[[patterns]]
id         = "そもそも"
name       = "そもそも"
jlpt       = ""
meaning_en = "In the first place; to begin with; first of all; the very (beginning/origin/etc.); original; first; fundamental"

[[patterns.steps]]
surface    = "そもそも"

