[[patterns]]
id         = "そこを"
name       = "そこを"
jlpt       = ""
meaning_en = "But; in spite of that"

[[patterns.steps]]
surface    = "そこ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "を"
pos1       = "助詞"
pos2       = "格助詞"

