[[patterns]]
id         = "それなりに"
name       = "それなりに"
jlpt       = ""
meaning_en = "In one’s own way; accompanying; proportionate; suitable; expected; agreeable; reasonable; one’s own; proper to"

[[patterns.steps]]
surface    = "それ"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "なり"
pos1       = "接尾辞"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

