[[patterns]]
id         = "たるや"
name       = "たるや"
jlpt       = ""
meaning_en = "When it comes to ~; speaking of"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "たり-断定"

[[patterns.steps]]
surface    = "や"
pos1       = "助詞"
pos2       = "終助詞"

