[[patterns]]
id         = "たなり"
name       = "たなり"
jlpt       = ""
meaning_en = "Without; while ~ staying; while ~ keep ~ing"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "た"

[[patterns.steps]]
surface    = "なり"
pos1       = "助詞"
pos2       = "接続助詞"

