[[patterns]]
id         = "たって"
name       = "たって"
jlpt       = ""
meaning_en = "Even if (someone says that); even if someone tries to; although"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "経つ"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

