[[patterns]]
id         = "だからと言って"
name       = "だからと言って"
jlpt       = ""
meaning_en = "However, it doesn't follow from this that ~; but it doesn't mean that ~; because of that"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

[[patterns.steps]]
surface    = "から"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

