[[patterns]]
id         = "だって"
name       = "だって"
jlpt       = ""
meaning_en = "Too; also; (not) ~ either; even; any; no matter what/who/how/etc."

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

[[patterns.steps]]
surface    = "って"
pos1       = "助詞"
pos2       = "副助詞"

