[[patterns]]
id         = "ちなみに"
name       = "ちなみに"
jlpt       = ""
meaning_en = "Incidentally; in this connection"

[[patterns.steps]]
surface    = "ちなみ"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

