[[patterns]]
id         = "ついては"
name       = "ついては"
jlpt       = ""
meaning_en = "Therefore; thus; so; because of this; for this reason; with regard to this"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "付く"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

