[[patterns]]
id         = "つもり"
name       = "つもり"
jlpt       = ""
meaning_en = "Intend to ~; be convinced that ~; believe; feel sure that ~; be going to; mean"

[[patterns.steps]]
surface    = "つもり"

