[[patterns]]
id         = "て仕方がない"
name       = "て仕方がない"
jlpt       = ""
meaning_en = "Cannot help ~ing; cannot stop feeling; (so ~ and) cannot control ~; so ~ and ~ cannot bare it; so; unbearably"

[[patterns.steps]]
surface    = "て"
pos1       = "接続詞"

[[patterns.steps]]
surface    = "仕方"

[[patterns.steps]]
surface    = "が"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

