[[patterns]]
id         = "て初めて"
name       = "て初めて"
jlpt       = ""
meaning_en = "Not until; only after; for the first time"

[[patterns.steps]]
surface    = "て"
pos1       = "接続詞"

[[patterns.steps]]
surface    = "初めて"
pos1       = "副詞"

