[[patterns]]
id         = "であろう"
name       = "であろう"
jlpt       = ""
meaning_en = "Probably"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "有る"

