[[patterns]]
id         = "という風に"
name       = "という風に"
jlpt       = ""
meaning_en = "In such a way that; in such a fashion to suggest/show (etc.) that; as if to say/show (etc.) that"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "風"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

