[[patterns]]
id         = "ということは"
name       = "ということは"
jlpt       = ""
meaning_en = "That; the fact that"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "こと"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

