[[patterns]]
id         = "ところが"
name       = "ところが"
jlpt       = ""
meaning_en = "However; but"

[[patterns.steps]]
surface    = "ところ"

[[patterns.steps]]
surface    = "が"
pos1       = "助詞"
pos2       = "格助詞"

