[[patterns]]
id         = "とする"
name       = "とする"
jlpt       = ""
meaning_en = "Feel ~; look ~"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "為る"

