[[patterns]]
id         = "ところから"
name       = "ところから"
jlpt       = ""
meaning_en = "Because; be caused by the fact that ~; from the fact that ~"

[[patterns.steps]]
surface    = "ところ"

[[patterns.steps]]
surface    = "から"
pos1       = "助詞"
pos2       = "格助詞"

