[[patterns]]
id         = "といったところだ"
name       = "といったところだ"
jlpt       = ""
meaning_en = "I would say ~; ~ is how I’d put it"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "た"

[[patterns.steps]]
surface    = "ところ"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

