[[patterns]]
id         = "との"
name       = "との"
jlpt       = ""
meaning_en = "That"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "の"
pos1       = "助詞"
pos2       = "格助詞"

