[[patterns]]
id         = "とうとう"
name       = "とうとう"
jlpt       = ""
meaning_en = "Finally; at (long) last; eventually; in the end; after all"

[[patterns.steps]]
pos1       = "形状詞"
base_form  = "蕩々"

