[[patterns]]
id         = "と同時に"
name       = "と同時に"
jlpt       = ""
meaning_en = "At the same time (as); at the time; when; as; while; as well as ~"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "同時"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

