[[patterns]]
id         = "と言うか"
name       = "と言うか"
jlpt       = ""
meaning_en = "Or; or rather; or I’d (rather) call it; or I may call it; or I’d (rather) say; or I may say"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "終助詞"

