[[patterns]]
id         = "と言うと"
name       = "と言うと"
jlpt       = ""
meaning_en = "When ~ mention; if ~ say that ~; when ~ say that ~; when it comes to"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "接続助詞"

