[[patterns]]
id         = "と言ったらない"
name       = "と言ったらない"
jlpt       = ""
meaning_en = "So; extremely; indescribably; indescribable; incredibly; awfully; terribly; cannot tell you/describe/etc. how; too much of"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "た"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

