[[patterns]]
id         = "どうにも"
name       = "どうにも"
jlpt       = ""
meaning_en = "Not ~ by any means; no matter how hard ~ try, ~ cannot ~; there is no way to ~; cannot do ~ at all"

[[patterns.steps]]
surface    = "どう"
pos1       = "副詞"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

