[[patterns]]
id         = "どちらかと言うと"
name       = "どちらかと言うと"
jlpt       = ""
meaning_en = "Rather; more like ~; more of ~; rather on the ~ side; rather than otherwise; more ~ than ~"

[[patterns.steps]]
surface    = "どちら"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "終助詞"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "接続助詞"

