[[patterns]]
id         = "どうか"
name       = "どうか"
jlpt       = ""
meaning_en = "Please"

[[patterns.steps]]
surface    = "どう"
pos1       = "副詞"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "副助詞"

