[[patterns]]
id         = "どうも"
name       = "どうも"
jlpt       = ""
meaning_en = "I don't know why but; I cannot manage to; just; from what I gather; seem; no matter how ~; I gather that ~; for some reason"

[[patterns.steps]]
surface    = "どう"
pos1       = "副詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

