[[patterns]]
id         = "なまじっか"
name       = "なまじっか"
jlpt       = ""
meaning_en = "Halfheartedly; slightly; thoughtlessly; unwisely; inadequately; imperfectly; sort of; a little; somewhat; a bit of"

[[patterns.steps]]
surface    = "なまじっか"
pos1       = "副詞"

