[[patterns]]
id         = "ならない"
name       = "ならない"
jlpt       = ""
meaning_en = "Cannot help -ing; irresistibly; unbearably"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "成る"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ない"

