[[patterns]]
id         = "ないことも"
name       = "ないことも"
jlpt       = ""
meaning_en = "It isn't the case that ~ not ~; it is not that ~ not ~"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

[[patterns.steps]]
surface    = "こと"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

