[[patterns]]
id         = "などと"
name       = "などと"
jlpt       = ""
meaning_en = "(things) like ~; ~ or something like"

[[patterns.steps]]
surface    = "など"
pos1       = "助詞"
pos2       = "副助詞"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

