[[patterns]]
id         = "なぜなら"
name       = "なぜなら"
jlpt       = ""
meaning_en = "The reason is that ~; because"

[[patterns.steps]]
surface    = "なぜ"
pos1       = "副詞"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

