[[patterns]]
id         = "なくて"
name       = "なくて"
jlpt       = ""
meaning_en = "Do not do something and ~; is not ~ and ~; because ~ do not do something"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

