[[patterns]]
id         = "ないしは"
name       = "ないしは"
jlpt       = ""
meaning_en = "From ~ to ~; between ~ and ~; or"

[[patterns.steps]]
surface    = "ないし"
pos1       = "接続詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

