[[patterns]]
id         = "なまじ"
name       = "なまじ"
jlpt       = ""
meaning_en = "Halfheartedly; slightly; thoughtlessly; unwisely; inadequately; imperfectly; sort of; a little; somewhat; a bit of"

[[patterns.steps]]
surface    = "なまじ"
pos1       = "副詞"

