[[patterns]]
id         = "なぜか"
name       = "なぜか"
jlpt       = ""
meaning_en = "I don’t know why; without knowing why; for an unknown reason"

[[patterns.steps]]
surface    = "なぜ"
pos1       = "副詞"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "副助詞"

