[[patterns]]
id         = "なお"
name       = "なお"
jlpt       = ""
meaning_en = "Still; even more; all the more for ~; additional; and; additionally; furthermore"

[[patterns.steps]]
surface    = "なお"
pos1       = "接続詞"

