[[patterns]]
id         = "にもなると"
name       = "にもなると"
jlpt       = ""
meaning_en = "When; if; as"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "成る"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "接続助詞"

