[[patterns]]
id         = "にいたっては"
name       = "にいたっては"
jlpt       = ""
meaning_en = "When it comes to ~; as for; for example"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "至る"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

