[[patterns]]
id         = "にしてからが"
name       = "にしてからが"
jlpt       = ""
meaning_en = "even"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "為る"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
surface    = "から"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "が"
pos1       = "助詞"
pos2       = "格助詞"

