[[patterns]]
id         = "にもなく"
name       = "いつにもなく"
jlpt       = ""
meaning_en = "Unusually; more ~ than usual (with も for emphasis)"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

