[[patterns]]
id         = "に向けた"
name       = "に向けた"
jlpt       = ""
meaning_en = "Toward; to; at; aiming at; targeting; for; for the purpose of; in order to"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "向ける"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "た"

