[[patterns]]
id         = "に当たり"
name       = "に当たり"
jlpt       = ""
meaning_en = "On the occasion of; at; in; before; prior to"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "当たる"

