[[patterns]]
id         = "に比べる"
name       = "に比べる"
jlpt       = ""
meaning_en = "Compared with/to; when compared with/to; in comparison to"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "比べる"

