[[patterns]]
id         = "の下で"
name       = "の下で"
jlpt       = ""
meaning_en = "Under; in; with"

[[patterns.steps]]
surface    = "の"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "下"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

