[[patterns]]
id         = "の無さ"
name       = "の無さ"
jlpt       = ""
meaning_en = "Lack of; absence of"

[[patterns.steps]]
surface    = "の"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

[[patterns.steps]]
surface    = "さ"
pos1       = "接尾辞"

