[[patterns]]
id         = "の関係で"
name       = "の関係で"
jlpt       = ""
meaning_en = "Because of"

[[patterns.steps]]
surface    = "の"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "関係"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

