[[patterns]]
id         = "はたして"
name       = "はたして"
jlpt       = ""
meaning_en = "Just as ~ though; as expected; really; in fact; sure enough; indeed; at all; lo and behold"

[[patterns.steps]]
surface    = "はたして"
pos1       = "副詞"

