[[patterns]]
id         = "はあれ"
name       = "はあれ"
jlpt       = ""
meaning_en = "Even though there is; although there is; there is ~ but"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
surface    = "あれ"
pos1       = "代名詞"

