[[patterns]]
id         = "はいけない"
name       = "はいけない"
jlpt       = ""
meaning_en = "Cannot do something; must not do something; don’t do something; should not do something"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "行く"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ない"

