[[patterns]]
id         = "は言うまでもなく"
name       = "は言うまでもなく"
jlpt       = ""
meaning_en = "Not to speak of; let alone; not to mention; to say nothing of"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "まで"
pos1       = "助詞"
pos2       = "副助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

