[[patterns]]
id         = "ひとつ"
name       = "ひとつ"
jlpt       = ""
meaning_en = "Give something a try"

[[patterns.steps]]
surface    = "ひと"
pos2       = "数詞"

[[patterns.steps]]
surface    = "つ"
pos1       = "接尾辞"

