[[patterns]]
id         = "まさか"
name       = "まさか"
jlpt       = ""
meaning_en = "Incredible; never thought; never dreamed; surely not; impossible; don't tell me that ~; not at all likely; absolutely not."

[[patterns.steps]]
surface    = "まさか"
pos1       = "副詞"

