[[patterns]]
id         = "ましてや"
name       = "ましてや"
jlpt       = ""
meaning_en = "To say nothing of; not to speak of; let alone; still more; much less; all the more reason why"

[[patterns.steps]]
surface    = "まして"
pos1       = "副詞"

[[patterns.steps]]
surface    = "や"
pos1       = "助詞"
pos2       = "副助詞"

