[[patterns]]
id         = "まして"
name       = "まして"
jlpt       = ""
meaning_en = "To say nothing of; not to speak of; let alone; still more; much less; all the more reason why"

[[patterns.steps]]
surface    = "まして"
pos1       = "副詞"

