[[patterns]]
id         = "または"
name       = "または"
jlpt       = ""
meaning_en = "Or; either ~ or ~"

[[patterns.steps]]
surface    = "また"
pos1       = "接続詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

