[[patterns]]
id         = "まで"
name       = "まで"
jlpt       = ""
meaning_en = "As far as; till; up to; until; through; even"

[[patterns.steps]]
surface    = "ま"
pos1       = "感動詞"

[[patterns.steps]]
surface    = "で"
pos1       = "接続詞"

