[[patterns]]
id         = "ましだ"
name       = "ましだ"
jlpt       = ""
meaning_en = "Better; less objectionable; preferable; might as well ~"

[[patterns.steps]]
pos1       = "形状詞"
base_form  = "増し"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

