[[patterns]]
id         = "みせる"
name       = "みせる"
jlpt       = ""
meaning_en = "Can manage to; will definitely do; am determined to"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "見せる"

