[[patterns]]
id         = "みる"
name       = "みる"
jlpt       = ""
meaning_en = "Do something and see; try to do something"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "見る"

