[[patterns]]
id         = "ればこそ"
name       = "ればこそ"
jlpt       = ""
meaning_en = "it is precisely because ~ that ~; only because ~; to the extent that ~"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "れる"

[[patterns.steps]]
surface    = "ば"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
surface    = "こそ"
pos1       = "助詞"
pos2       = "係助詞"

