[[patterns]]
id         = "をめぐる"
name       = "をめぐる"
jlpt       = ""
meaning_en = "Centering around; in connection with; over; concerning; regarding; with regard to"

[[patterns.steps]]
surface    = "を"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "巡る"

