[[patterns]]
id         = "を介した"
name       = "を介した"
jlpt       = ""
meaning_en = "Through; via; by means of; by ~ing"

[[patterns.steps]]
surface    = "を"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "介する"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "た"

