[[patterns]]
id         = "んとする"
name       = "んとする"
jlpt       = ""
meaning_en = "Try to do; be about to"

[[patterns.steps]]
surface    = "ん"
pos1       = "感動詞"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "為る"

