[[patterns]]
id         = "一つには"
name       = "一つには"
jlpt       = ""
meaning_en = "Partly; for one thing"

[[patterns.steps]]
surface    = "一"
pos2       = "数詞"

[[patterns.steps]]
surface    = "つ"
pos1       = "接尾辞"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

