[[patterns]]
id         = "一応"
name       = "一応"
jlpt       = ""
meaning_en = "For the time being; for the present; for now; tentatively; for formality’s sake; nominally; kind of; sort of"

[[patterns.steps]]
surface    = "一応"

