[[patterns]]
id         = "一旦"
name       = "一旦"
jlpt       = ""
meaning_en = "Once; for a time; temporarily; for the moment; for the present; now"

[[patterns.steps]]
surface    = "一旦"
pos1       = "副詞"

