[[patterns]]
id         = "並びに"
name       = "並びに"
jlpt       = ""
meaning_en = "And; both ~ and ~; as well as"

[[patterns.steps]]
surface    = "並び"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

