[[patterns]]
id         = "中を"
name       = "中を"
jlpt       = ""
meaning_en = "In the midst of; when; while; through; among"

[[patterns.steps]]
surface    = "中"

[[patterns.steps]]
surface    = "を"
pos1       = "助詞"
pos2       = "格助詞"

