[[patterns]]
id         = "何しろ"
name       = "何しろ"
jlpt       = ""
meaning_en = "As a matter of fact; no matter what; believe it or not; you may be surprised, but ~; in fact; unbelievably"

[[patterns.steps]]
surface    = "何しろ"
pos1       = "副詞"

