[[patterns]]
id         = "何らかの"
name       = "何らかの"
jlpt       = ""
meaning_en = "Some; some kind of"

[[patterns.steps]]
surface    = "何"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "ら"
pos1       = "接尾辞"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "副助詞"

[[patterns.steps]]
surface    = "の"
pos1       = "助詞"
pos2       = "格助詞"

