[[patterns]]
id         = "何とか"
name       = "何とか"
jlpt       = ""
meaning_en = "Somehow; in some way; in one way or another; manage to"

[[patterns.steps]]
surface    = "何"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "と"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "か"
pos1       = "助詞"
pos2       = "副助詞"

