[[patterns]]
id         = "何でも"
name       = "何でも"
jlpt       = ""
meaning_en = "I don't know for sure, but"

[[patterns.steps]]
surface    = "何"
pos1       = "代名詞"

[[patterns.steps]]
surface    = "で"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

