[[patterns]]
id         = "例の"
name       = "例の"
jlpt       = ""
meaning_en = "The ~ (in question); that (same); the usual"

[[patterns.steps]]
surface    = "例"

[[patterns.steps]]
surface    = "の"
pos1       = "助詞"
pos2       = "格助詞"

