[[patterns]]
id         = "割には"
name       = "割には"
jlpt       = ""
meaning_en = "For; despite; although; (not) as much as; (not) ~ because of that; considering"

[[patterns.steps]]
surface    = "割"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
surface    = "は"
pos1       = "助詞"
pos2       = "係助詞"

