[[patterns]]
id         = "単に"
name       = "単に"
jlpt       = ""
meaning_en = "Just; only; simply; no more than; nothing but; solely; merely; alone"

[[patterns.steps]]
surface    = "単に"
pos1       = "副詞"

