[[patterns]]
id         = "単位で"
name       = "単位で"
jlpt       = ""
meaning_en = "By the; in sets/groups/lots/etc. of; in multiples of; each; every"

[[patterns.steps]]
surface    = "単位"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

