[[patterns]]
id         = "向け"
name       = "向け"
jlpt       = ""
meaning_en = "For; made for; for the use of; aimed at; directed towards; (directed/shipped/etc.) to"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "向ける"

