[[patterns]]
id         = "堪らない"
name       = "堪らない"
jlpt       = ""
meaning_en = "Unbearably ~; extremely; be dying to do ~"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "堪る"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ない"

