[[patterns]]
id         = "如何"
name       = "如何"
jlpt       = ""
meaning_en = "How; what; (depending on) how/what; (according to) how/what; depend on"

[[patterns.steps]]
pos1       = "形状詞"
base_form  = "如何"

