[[patterns]]
id         = "思われる"
name       = "思われる"
jlpt       = ""
meaning_en = "Seem; appear; apparently"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "思う"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "れる"

