[[patterns]]
id         = "思うに"
name       = "思うに"
jlpt       = ""
meaning_en = "In my view; it seems to me that ~; when I think (about ~); considering"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "思う"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

