[[patterns]]
id         = "思えば"
name       = "思えば"
jlpt       = ""
meaning_en = "Come ot think of it; when I think back; on reflection"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "思う"

[[patterns.steps]]
surface    = "ば"
pos1       = "助詞"
pos2       = "接続助詞"

