[[patterns]]
id         = "方をする"
name       = "方をする"
jlpt       = ""
meaning_en = "Do something in a ~ fashion/manner/way"

[[patterns.steps]]
surface    = "方"

[[patterns.steps]]
surface    = "を"
pos1       = "助詞"
pos2       = "格助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "為る"

