[[patterns]]
id         = "更に"
name       = "更に"
jlpt       = ""
meaning_en = "Even ~er; even more; additional; more; further; furthermore; in addition"

[[patterns.steps]]
surface    = "更に"
pos1       = "接続詞"

