[[patterns]]
id         = "言ってみれば"
name       = "言ってみれば"
jlpt       = ""
meaning_en = "Figuratively speaking; so to speak; metaphorically speaking; in a manner of saying"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "て"
pos1       = "助詞"
pos2       = "接続助詞"

[[patterns.steps]]
pos1       = "動詞"
pos2       = "非自立可能"
base_form  = "見る"

[[patterns.steps]]
surface    = "ば"
pos1       = "助詞"
pos2       = "接続助詞"

