[[patterns]]
id         = "言うまでもない"
name       = "言うまでもない"
jlpt       = ""
meaning_en = "It is needless to say that ~; needless to say; it goes without saying"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
surface    = "まで"
pos1       = "助詞"
pos2       = "副助詞"

[[patterns.steps]]
surface    = "も"
pos1       = "助詞"
pos2       = "係助詞"

[[patterns.steps]]
pos1       = "形容詞"
base_form  = "無い"

