[[patterns]]
id         = "言わず"
name       = "言わず"
jlpt       = ""
meaning_en = "A, B and many other ~; A, B and every ~ else; including: whether X or Y"

[[patterns.steps]]
pos1       = "動詞"
base_form  = "言う"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "ず"

