[[patterns]]
id         = "逆に"
name       = "逆に"
jlpt       = ""
meaning_en = "Contrary to one's expectation; contrary to one's intention; conversely"

[[patterns.steps]]
surface    = "逆"

[[patterns.steps]]
pos1       = "助動詞"
base_form  = "だ"

