[[patterns]]
id         = "通りに"
name       = "通りに"
jlpt       = ""
meaning_en = "(in) the same way as; (in) the way; as"

[[patterns.steps]]
surface    = "通り"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

