[[patterns]]
id         = "面"
name       = "面"
jlpt       = ""
meaning_en = "(on) the side of; (from) the aspect of; (from) the standpoint/viewpoint of; in terms of"

[[patterns.steps]]
surface    = "面"

