[[patterns]]
id         = "風に"
name       = "風に"
jlpt       = ""
meaning_en = "In ~ manner; after ~ style; a la ~; like"

[[patterns.steps]]
surface    = "風"

[[patterns.steps]]
surface    = "に"
pos1       = "助詞"
pos2       = "格助詞"

